<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/models/Models.glb
-->

<script lang="ts">
  //<!-- import { Group } from 'three' -->
  import { AddEquation, CustomBlending, Group, LessEqualDepth, OneFactor } from 'three';
  import * as THREE from 'three'; // Import THREE
  import { T, forwardEventHandlers } from '@threlte/core';
  import { useGltf, useGltfAnimations } from '@threlte/extras';
  import { useTexture } from '@threlte/extras';

  export const ref = new Group();

  const gltf = useGltf('/models/Models.glb');
  const map = useTexture('textures/energy-beam-opacity.png');
  export const { actions, mixer } = useGltfAnimations(gltf, ref);

  $: $actions['Armature|Take 001|BaseLayer']?.play();
  const component = forwardEventHandlers();

  </script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.5} position={[0, -3, 0]} >
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="gold1"
          geometry={gltf.nodes.gold1.geometry}
          material={gltf.materials['musa:gold']}
          skeleton={gltf.nodes.gold1.skeleton}
        />
        <T.SkinnedMesh
          name="Material_Belt"
          geometry={gltf.nodes.Material_Belt.geometry}
          material={gltf.materials['musa:blet']}
          skeleton={gltf.nodes.Material_Belt.skeleton}
        />
        <T.SkinnedMesh
          name="Material_Clothes"
          geometry={gltf.nodes.Material_Clothes.geometry}
          material={gltf.materials['musa:clothes']}
          skeleton={gltf.nodes.Material_Clothes.skeleton}
        />
        <T.SkinnedMesh
          name="Material_Eyes"
          geometry={gltf.nodes.Material_Eyes.geometry}
          material={gltf.materials['musa:eyes']}
          skeleton={gltf.nodes.Material_Eyes.skeleton}
        />
        <T.SkinnedMesh
          name="Material_Gems"
          geometry={gltf.nodes.Material_Gems.geometry}
          material={gltf.materials['musa:gem']}
          skeleton={gltf.nodes.Material_Gems.skeleton}
        />
        <T.SkinnedMesh
          name="Material_Hair"
          geometry={gltf.nodes.Material_Hair.geometry}
          material={gltf.materials['musa:hair']}
          skeleton={gltf.nodes.Material_Hair.skeleton}
        />
        <T.SkinnedMesh
          name="Material_Pants"
          geometry={gltf.nodes.Material_Pants.geometry}
          material={gltf.materials['musa:pants']}
          skeleton={gltf.nodes.Material_Pants.skeleton}
        />
        <T.SkinnedMesh
          name="Material_skin"
          geometry={gltf.nodes.Material_skin.geometry}
          material={gltf.materials['musa:skin']}
          skeleton={gltf.nodes.Material_skin.skeleton}
        />
        <T.SkinnedMesh
          name="u_nobody_smooth_rig02_finished_01modelgeo"
          geometry={gltf.nodes.u_nobody_smooth_rig02_finished_01modelgeo.geometry}
          material={gltf.materials.standardSurface1}
          skeleton={gltf.nodes.u_nobody_smooth_rig02_finished_01modelgeo.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
